---
  - name: install python 3.6
    become: yes
    pkgng: name=python36 state=present

  - name: create python symlink to /usr/bin
    become: yes
    file: src=/usr/local/bin/python3.6 dest=/usr/bin/python state=link

  - name: create python symlink to /usr/local/bin
    become: yes
    file: src=/usr/local/bin/python3.6 dest=/usr/local/bin/python state=link
