---
- hosts: all
  vars_files:
    - vaults/prod.yml
  vars:
    ansible_python_interpreter: /usr/local/bin/python3.6
    domain_name: api.prod.hikster.com
    short_name: hikster
    program_name: prod
    app_database: hikster_api_prod
    app_django_settings: hikster.settings.prod_api
    app_git_version: master
    app_git_repo: git@bitbucket.org:hikster/hikster.git
  roles:
     - os_updates
     - os_devel
     - os_nfs
     - os_geoip_databases
     - os_pgsql_install
     - os_pgsql_start
     - os_postgis_install
     - os_supervisord
     - os_nginx
     # - os_redis
     - pgsql_user
     - pgsql_database_postgis
     - app_dirs
     - app_source
     - pgsql_backup
     - app_django
     - svr_prod
