/**
 * Created by fbrousseau on 2016-03-11.
 */
export const RECV_SHOWCASE_ERROR = "RECV_SHOWCASE_ERROR";
export const REQ_SHOWCASE_DATA = "REQ_SHOWCASE_DATA";
export const RECV_SHOWCASE_DATA = "RECV_SHOWCASE_DATA";

export const SUBMIT_HIKE_SEARCH_FORM = "SUBMIT_HIKE_SEARCH_FORM";
export const RECEIVE_SEARCHED_HIKES = "RECEIVE_SEARCHED_HIKES";
export const RECEIVE_SEARCHED_HIKE_ERROR = "RECEIVE_SEARCH_ERROR";

export const SUBMIT_LOCATION_SEARCH_FORM = "SUBMIT_LOCATION_SEARCH_FORM";
export const RECEIVE_SEARCHED_LOCATION = "RECEIVE_SEARCHED_LOCATION";
export const RECEIVE_SEARCHED_LOCATION_ERROR = "RECEIVE_SEARCHED_LOCATION_ERROR";

export const REQ_POI_DATA = "REQ_POI_DATA";
export const RECV_POI_DATA = "RECV_POI_DATA";
export const RECV_POI_ERROR = "RECV_POI_ERROR";

export const REQ_HIKE_DATA = "REQ_HIKE_DATA";
export const RECV_HIKE_DATA = "RECV_HIKE_DATA";
export const RECV_HIKE_ERROR = "RECV_HIKE_ERROR";

export const SUBMIT_NEWSLETTER_FORM = "SUBMIT_NEWSLETTER_FORM";
export const RECEIVE_CONFIRMATION = "RECEIVE_CONFIRMATION";
export const RECEIVE_ERROR = "RECEIVE_ERROR";

export const SELECT_HIKE_FROM_LIST = "SELECT_HIKE_FROM_LIST";
export const SELECT_POI_FROM_LIST = "SELECT_POI_FROM_LIST";
export const SELECT_NETWORK_FROM_LIST = "SELECT_NETWORK_FROM_LIST";

export const CLEAR_HIKE_FROM_LIST = "CLEAR_HIKE_FROM_LIST";

export const SELECT_DYNAMIC_LAYER = "SELECT_DYNAMIC_LAYER";
export const POI_LEGEND_CHANGE = "POI_LEGEND_CHANGE";

// Pagination actions
export const PREVIOUS_PAGE = "PREVIOUS_PAGE";
export const NEXT_PAGE = "NEXT_PAGE";


// PubSub actions
export const HIGHLIGHT_HIKE = "HIGHLIGHT_HIKE";
export const HIGHLIGHT_HIKE_OFF = "HIGHLIGHT_HIKE_OFF";
export const ZOOM_TO_HIKE = "ZOOM_TO_HIKE";
